name: Validate schema

on:
  push:
    branches:
      - main
    paths:
      - schemas/**
  pull_request:
    branches:
      - main
    paths:
      - schemas/**

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate JSON Schema
      uses: walbo/validate-json@v1.1.0
      with:
        files: 
          schemas/schemas/*.json
          schemas/definitions/*.json
        print-valid-files: true
        schema-version: draft-07
